// <auto-generated />
namespace Computer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ExcludeFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExcludeFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "202005301940261_ExcludeFiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
